export const HeaderTable = [
  { dataIndex: "Dokumen Pendukung" },
  { dataIndex: "Konsumsi Rapat" },
  { dataIndex: "Belanja Bahan / ATK / Cetak" },
  { dataIndex: "Belanja Sewa" },
  { dataIndex: "Honor Narasumber / Moderator" },
  { dataIndex: "Jasa Konsultan / Lainnya" },
  { dataIndex: "Perjalanan Dinas Biasa" },
  { dataIndex: "Perjalanan Dinas Dalam Kota" },
  { dataIndex: "Perjalanan Dinas Paket Meeting Dalam Kota" },
  { dataIndex: "Perjalanan Dinas Paket Meeting Luar Kota" },
  { dataIndex: "Perjalanan Dinas Luar Negeri" },
  { dataIndex: "Pembelian Barang Dan Modal " },
];

export const HeaderTableChecking = [
  { HTChecking: "No" },
  { HTChecking: "Kode Mak" },
  { HTChecking: "Deskripsi" },
  { HTChecking: "Keterangan" },
  { HTChecking: "Nilai" },
  { HTChecking: "Tanggal Pengajuan" },
  { HTChecking: "Tanggal Selesai" },
  { HTChecking: "Verifikator" },
];

export const DokumenPendukung = [
  { dpIndex: "Kode Akun (MAK)" },
  { dpIndex: "Kuitansi/Invoice" },
  { dpIndex: "Undangan" },
  { dpIndex: "Daftar Hadir/Absensi" },
  { dpIndex: "Notulensi/Laporan" },
  { dpIndex: "Dokumentasi" },
  { dpIndex: "Paparan" },
  { dpIndex: "Rencana Penarikan Anggaran (RPA)" },
  { dpIndex: "Surat Tugas" },
  { dpIndex: "SPD Asli Cap Basah Lengkap Dengan Jabatan, Nama, dan NIP" },
  { dpIndex: "SPPD Rampung" },
  { dpIndex: "Surat Pernyataan Pengeluaran Riil" },
  { dpIndex: "Surat Pernyataan Tanggung Jawab Mutlak" },
  { dpIndex: "Copy CV, KTP, NPWP" },
  {
    dpIndex:
      "Tiket dan Boarding Pass PP (Asli) Jika Menggunakan Angkutan Udara",
  },
  { dpIndex: "Kuitansi Hotel Jika Menginap / Tidak Ditanggung (Asli)" },
  { dpIndex: "Formulir Bukti Pelaksanaan Perjalanan Dinas (Asli) Cap Basah" },
  { dpIndex: "Copy Paspor (Cap)" },
  { dpIndex: "Copy SPK/Kontrak" },
  { dpIndex: "Berita Acara Serah Terima Hasil Pekerjaan" },
  { dpIndex: "Berita Acara Pembayaran" },
  { dpIndex: "Faktur Pajak (Jika Ada)" },
  { dpIndex: "Bukti Bayar Pajak (Jika Menggunakan dana APBN)" },
  { dpIndex: "Garansi Bank (Jika Ada)" },
  { dpIndex: "Tanda Terima Honor" },
];
