export const KonsumsiRapat = {
  kode_mak: "521211",
  kuitansi: false,
  undangan: false,
  daftar_hadir: false,
  notulensi: false,
  dokumentasi: false,
  paparan: null,
  rpa: null,
  surat_tugas: null,
  spd: null,
  sppd: null,
  sp_pengeluaran: null,
  sptj_mutlak: null,
  copy_personal: null,
  boarding_pass: null,
  kwitansi_hotel: null,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: null,
  ba_serah_terima: null,
  ba_pembayaran: null,
  faktur_pajak: null,
  bp_apbn: null,
  garansi_bank: null,
  honor: null,
};

export const BelanjaBahan = {
  kode_mak: "521211/521811",
  kuitansi: false,
  undangan: null,
  daftar_hadir: null,
  notulensi: null,
  dokumentasi: false,
  paparan: null,
  rpa: null,
  surat_tugas: null,
  spd: null,
  sppd: null,
  sp_pengeluaran: null,
  sptj_mutlak: null,
  copy_personal: null,
  boarding_pass: null,
  kwitansi_hotel: null,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: null,
  ba_serah_terima: null,
  ba_pembayaran: null,
  faktur_pajak: false,
  bp_apbn: false,
  garansi_bank: null,
  honor: null,
};

export const BelanjaSewa = {
  kode_mak: "522141",
  kuitansi: false,
  undangan: null,
  daftar_hadir: null,
  notulensi: null,
  dokumentasi: false,
  paparan: null,
  rpa: null,
  surat_tugas: null,
  spd: null,
  sppd: null,
  sp_pengeluaran: null,
  sptj_mutlak: null,
  copy_personal: null,
  boarding_pass: null,
  kwitansi_hotel: null,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: false,
  ba_serah_terima: false,
  ba_pembayaran: false,
  faktur_pajak: false,
  bp_apbn: false,
  garansi_bank: false,
  honor: null,
};

export const HonorNarasumber = {
  kode_mak: "522151",
  kuitansi: false,
  undangan: false,
  daftar_hadir: false,
  notulensi: null,
  dokumentasi: null,
  paparan: false,
  rpa: false,
  surat_tugas: null,
  spd: null,
  sppd: null,
  sp_pengeluaran: null,
  sptj_mutlak: false,
  copy_personal: false,
  boarding_pass: null,
  kwitansi_hotel: null,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: null,
  ba_serah_terima: null,
  ba_pembayaran: null,
  faktur_pajak: null,
  bp_apbn: false,
  garansi_bank: null,
  honor: null,
};

export const JasaKonsultan = {
  kode_mak: "522131/522191",
  kuitansi: false,
  undangan: null,
  daftar_hadir: false,
  notulensi: false,
  dokumentasi: null,
  paparan: null,
  rpa: false,
  surat_tugas: null,
  spd: null,
  sppd: null,
  sp_pengeluaran: null,
  sptj_mutlak: null,
  copy_personal: null,
  boarding_pass: null,
  kwitansi_hotel: null,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: false,
  ba_serah_terima: false,
  ba_pembayaran: false,
  faktur_pajak: null,
  bp_apbn: false,
  garansi_bank: false,
  honor: false,
};

export const PDBiasa = {
  kode_mak: "524111",
  kuitansi: false,
  undangan: false,
  daftar_hadir: null,
  notulensi: false,
  dokumentasi: false,
  paparan: null,
  rpa: null,
  surat_tugas: false,
  spd: false,
  sppd: false,
  sp_pengeluaran: false,
  sptj_mutlak: false,
  copy_personal: null,
  boarding_pass: false,
  kwitansi_hotel: false,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: null,
  ba_serah_terima: null,
  ba_pembayaran: null,
  faktur_pajak: null,
  bp_apbn: null,
  garansi_bank: null,
  honor: null,
};

export const PDDalamKota = {
  kode_mak: "524133",
  kuitansi: false,
  undangan: false,
  daftar_hadir: null,
  notulensi: false,
  dokumentasi: false,
  paparan: false,
  rpa: null,
  surat_tugas: false,
  spd: null,
  sppd: null,
  sp_pengeluaran: null,
  sptj_mutlak: null,
  copy_personal: null,
  boarding_pass: null,
  kwitansi_hotel: null,
  form_ppd: false,
  copy_paspor: null,
  copy_spk: null,
  ba_serah_terima: null,
  ba_pembayaran: null,
  faktur_pajak: null,
  bp_apbn: null,
  garansi_bank: null,
  honor: null,
};

export const PDPMeetingDalamKota = {
  kode_mak: "524114",
  kuitansi: false,
  undangan: false,
  daftar_hadir: false,
  notulensi: false,
  dokumentasi: false,
  paparan: null,
  rpa: null,
  surat_tugas: null,
  spd: null,
  sppd: null,
  sp_pengeluaran: null,
  sptj_mutlak: null,
  copy_personal: null,
  boarding_pass: null,
  kwitansi_hotel: null,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: false,
  ba_serah_terima: false,
  ba_pembayaran: false,
  faktur_pajak: null,
  bp_apbn: null,
  garansi_bank: null,
  honor: null,
};

export const PDPMeetingLuarKota = {
  kode_mak: "524119",
  kuitansi: false,
  undangan: false,
  daftar_hadir: null,
  notulensi: false,
  dokumentasi: false,
  paparan: null,
  rpa: null,
  surat_tugas: false,
  spd: false,
  sppd: false,
  sp_pengeluaran: false,
  sptj_mutlak: false,
  copy_personal: null,
  boarding_pass: false,
  kwitansi_hotel: false,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: null,
  ba_serah_terima: null,
  ba_pembayaran: null,
  faktur_pajak: null,
  bp_apbn: null,
  garansi_bank: null,
  honor: null,
};

export const PDLuarNegeri = {
  kode_mak: "524219",
  kuitansi: false,
  undangan: false,
  daftar_hadir: null,
  notulensi: false,
  dokumentasi: false,
  paparan: null,
  rpa: null,
  surat_tugas: false,
  spd: false,
  sppd: false,
  sp_pengeluaran: false,
  sptj_mutlak: false,
  copy_personal: null,
  boarding_pass: false,
  kwitansi_hotel: false,
  form_ppd: false,
  copy_paspor: false,
  copy_spk: null,
  ba_serah_terima: null,
  ba_pembayaran: null,
  faktur_pajak: null,
  bp_apbn: null,
  garansi_bank: null,
  honor: null,
};

export const PembelianBarang = {
  kode_mak: "532111/536111",
  kuitansi: false,
  undangan: null,
  daftar_hadir: null,
  notulensi: null,
  dokumentasi: false,
  paparan: null,
  rpa: null,
  surat_tugas: null,
  spd: null,
  sppd: null,
  sp_pengeluaran: null,
  sptj_mutlak: null,
  copy_personal: null,
  boarding_pass: null,
  kwitansi_hotel: null,
  form_ppd: null,
  copy_paspor: null,
  copy_spk: false,
  ba_serah_terima: false,
  ba_pembayaran: false,
  faktur_pajak: false,
  bp_apbn: false,
  garansi_bank: false,
  honor: null,
};
